### ISSUE TITLE
服务端建议

### ISSUE THREAD

**Issue by gkzhb** [leeggco/agefans_ex#2]
* 目前插件连接不上服务器（表现为无法登陆，没有追番的按钮），服务端似乎是挂了，也可能是防火墙或其它的问题
* 服务端使用的是 ip + 端口访问，希望能分配一个域名并使用反向代理 + https
* 还有一点是之前服务端的 express 代码仓库是开源的，现在是改成 private 了嘛？我个人的一个建议是希望能开源服务端代码，然后在插件中可以修改默认的服务端地址，从而允许自建服务端。

补充一个功能需求：
希望服务端支持独立的网页访问数据，在手机上因为无法安装 chrome 插件所以很难看到自己的追番或者历史记录，如果有网页前端的话会方便很多。

**Comment by leeggco** [comment]
非常抱歉出现了问题，凌晨时候我也发现了这个问题，后面恢复了。

目前暂时没有可以使用的备案域名，后续我备案一个解析上去。
服务端是private了，代码整理后再开源，最近也比较忙。

最后的功能需求很好，在域名备案下来或许可以加上。

再此致歉，感谢支持。

**Comment by gkzhb** [comment]
关于移动端访问，我做了一个网站 http://agex.gkzhb.tk/ （仓库链接：https://github.com/gkzhb/agex-web ）可以查看历史和收藏，不知作者是否介意~ 如有不便我会关闭仓库和网站。

**Comment by leeggco** [comment]
> 关于移动端访问，我做了一个网站 http://agex.gkzhb.tk/ （仓库链接：https://github.com/gkzhb/agex-web ）可以查看历史和收藏，不知作者是否介意~ 如有不便我会关闭仓库和网站。

哇，不介意的，做得棒呀！

**Comment by leeggco** [comment]
> 关于移动端访问，我做了一个网站 http://agex.gkzhb.tk/ （仓库链接：https://github.com/gkzhb/agex-web ）可以查看历史和收藏，不知作者是否介意~ 如有不便我会关闭仓库和网站。

这个不错啊，哈哈，那我省下做移动端的功夫了 😁

**Comment by zhixuan666** [comment]
关于安全问题 （可能也不需要）
----
resp.body + user.token 导出md5 加到请头上

在客户端比对

**Comment by leeggco** [comment]
安全方面后面可以提升下，现在似乎还不太需要
