### ISSUE TITLE
大哥，这个网站迁移了，劳烦修改一下

### ISSUE THREAD

**Issue by 1157612017** [leeggco/agefans_ex#7]
网站迁移了

**Comment by EwigL** [comment]
解压crx包，修改manifest.json文件可以暂时继续使用
![如图](https://cdn.jsdelivr.net/gh/xingjiahui/CDN@latest/2020/11/28/25c3e6ec39d976789c4ac30b5581226d.png)

**Comment by zhixuan2333** [comment]
> > 网站迁移了
> 
> 解压crx包，修改manifest.json文件可以暂时继续使用
> ![如图](https://camo.githubusercontent.com/a63a167e33ad9154244324e4036ae6ac0ea05c48eef1defeb7a1ce18d2948093/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f78696e676a69616875692f43444e406c61746573742f323032302f31312f32382f32356333653665633339643937363738396334616333306235353831323236642e706e67)

还有修改/js/content-script.js文件

在 [https://github.com/zhixuan666/agefans_ex](https://github.com/zhixuan666/agefans_ex) 已更改

**Comment by leeggco** [comment]
噢！ 我重新打包上架谷歌商店吧

**Comment by leeggco** [comment]
我提交到谷歌商店了，最新版本是1.0.33，重新安装就可以正常使用了。：D

**Comment by QSRNC** [comment]
这样以前点过追番的数据就都没有了吗😂

**Comment by zhixuan666** [comment]
> 我提交到谷歌商店了，最新版本是1.0.33，重新安装就可以正常使用了。：D

最新版本不是1.0.34吗？

**Comment by leeggco** [comment]
> 最新版本不是1.0.34吗？

对，用最新的就好了咯
